# App to build and share containerised applications and microservices
cask "docker-desktop"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Music streaming service
cask "spotify"
# Open-source code editor
cask "visual-studio-code"
# Video communication and virtual meeting platform
cask "zoom"
vscode "ms-vscode-remote.remote-containers"
vscode "vscodevim.vim"
